version: '3'

services:
  app:
      restart: "on-failure"
      build:
        context: .
      ports:
          - 8000:8000
      volumes:
          - ./app:/app
      command: >
          sh -c "daphne -b 0.0.0.0 -p 8000 app.asgi:application"
      env_file:
          - ./.env
      depends_on:
          - redis
          - db

  redis:
        restart: "on-failure"
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - redisdata:/data

  frontend:
    build: ./Frontend
    volumes:
      - ./Frontend:/Frontend


  db:
    restart: always
    image: kartoza/postgis:12.0
    ports:
        - 5432:5432
    volumes:
        - postgres_data:/var/lib/postgresql
    env_file:
        - ./database.env
  
  nginx:
    build: ./nginx
    ports:
        - 80:80
    volumes:
        - ./Frontend/:/usr/share/nginx/html/
       
    depends_on:
        - app
    
volumes:
  .:
  redisdata:
  Frontend:
  postgres_data:
  app:
  